In [81]:
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()

X, y = iris.data, iris.target

In [82]:
X.shape, y.shape

((150, 4), (150,))

In [83]:
data = np.hstack((X, y.reshape(150, 1)))
np.random.shuffle(data)
train, test = data[0:80], data[81:101]
trainX, trainY, testX, testY = np.delete(train, 4, 1), train[:, 4], np.delete(test, 4, 1), test[:, 4]
trainX.shape, trainY.shape, testX.shape, testY.shape

((80, 4), (80,), (20, 4), (20,))

In [84]:
class MinMaxScaler():

    def __init__(self):

        self.mins = None
        self.maxs = None

    def fit(self, data):

        self.maxs = data.max(axis=0)
        self.mins = data.min(axis=0)

        return None
    
    def transform(self, data):

        transformed = []
        for i in range(data.shape[1]):
            
            std = (data[:, i] - self.mins[i]) / (self.maxs[i] - self.mins[i])
            transformed.append(std)
        
        return np.array(transformed).T
    
    def fit_transform(self, data):

        self.fit(data)
        return self.transform(data)

In [85]:
X[:3], X[:3].min(axis=0), X[:3].max(axis=0)

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2]]),
 array([4.7, 3. , 1.3, 0.2]),
 array([5.1, 3.5, 1.4, 0.2]))

In [86]:
X[:3].shape

(3, 4)

In [87]:
data = np.array([[-1, 2], [-0.5, 6], [0, 10], [1, 18]])
scaler = MinMaxScaler()
print(scaler.fit_transform(data))
print(scaler.maxs)
print(scaler.mins)
print(scaler.transform(np.array([[2, 2]])))

[[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [1.   1.  ]]
[ 1. 18.]
[-1.  2.]
[[1.5 0. ]]
